Add message handler and tests: #0000023
KasperskyLab/knp pull request #27
Opened 2024-11-29 10:26 UTC by a-vartenkov

Add message handler class and three basic functors.

kWTA functor which selects k random spikes out of a message, 
Group WTA which selects a group or a few groups based on which groups have the largest number of spikes. 
Union handler which uses a union set operation on spike indices.

Add tests for message handler class and for all added functors.

2024-11-29 10:51 UTC, artiomn requested changes
Проверь хуки прекоммита.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +//
Шапка комментария.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +    // Fill groups in
Точки после комментов.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +    for (auto spike : spikes)
const ссылка.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +
Две пустые строки.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +    auto &msg = messages[0];
const

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +        for (auto spike : spikes_per_group[i]) result.push_back(spike);
const&

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +    // Sort groups by number of elements
Точки.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +
Лишняя пустая строка.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +
Лишняя пустая строка. У тебя явно не работают хуки прекоммита.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +
Лишняя пустая строка. См. выше.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +     * @note for internal use, don't try to call it manually.
Нафига он тогда в паблике торчит?

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +
Лишняя пустая строка.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +class KWtaRandomHandler
Что значит `K`?

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +     * @brief Constructor
Точки.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +
Лишняя пустая строка.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +
Лишняя пустая строка.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +     * @brief Functor operator.
Просто оператор вызова.

2024-11-29 10:51 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +    explicit GroupWtaRandomHandler(
Зачем тут explicit?

2024-11-29 10:51 UTC, artiomn commented on knp/tests/framework/message_handler_test.cpp
> +    // the intervals are [0, 1, 2], [3, 4, 5], [6, 7, 8], [9, ...]
Точки.

2024-11-29 11:02 UTC, a-vartenkov commented on knp/base-framework/include/knp/framework/message_handler.h
> +    explicit GroupWtaRandomHandler(
Чтобы из вектора implicitly не конвертировался.

2024-11-29 11:09 UTC, a-vartenkov commented on knp/base-framework/impl/message_handler.cpp
> +    for (auto spike : spikes)
На элементарный тип? Вроде бы это считается неэффективно, разве не? В принципе скорее всего-то для компилятора всё равно, но чисто из принципа.

2024-11-29 11:12 UTC, a-vartenkov commented on knp/base-framework/impl/message_handler.cpp
> +    auto &msg = messages[0];
Тут делается случайный выбор k значений. Самый дешёвый способ его сделать, который я нашёл, это swap in-place, он требует модификации. Иначе лишнее копирование сообщения. К счастью а) порядок спайков внутри сообщения не информативен и б) эндпойнт возвращает по значению, то есть этот swap ничего не портит. Можно сделать иначе, но это лишнее копирование.

2024-11-29 11:14 UTC, a-vartenkov commented on knp/base-framework/impl/message_handler.cpp
> +        for (auto spike : spikes_per_group[i]) result.push_back(spike);
То же самое: spike это по сути int, на него тоже нужна константная ссылка?

2024-11-29 11:16 UTC, a-vartenkov commented on knp/base-framework/include/knp/framework/message_handler.h
> +     * @note for internal use, don't try to call it manually.
Его вызывает ModelExecutor. Можно, наверное, сделать friend?

2024-11-29 11:18 UTC, a-vartenkov commented on knp/base-framework/include/knp/framework/message_handler.h
> +class KWtaRandomHandler
In many practical cases, there is not only one single neuron which becomes active but there are exactly k neurons which become active for a fixed number k. This principle is referred to as **k-winners-take-all**. (c) wiki

2024-11-29 16:44 UTC, a-vartenkov commented on knp/base-framework/impl/message_handler.cpp
> +
Добавил

2024-11-29 17:13 UTC, artiomn commented on knp/base-framework/include/knp/framework/message_handler.h
> +     * @note for internal use, don't try to call it manually.
Такое ощущение, что здесь инверсия зависимостей: экзекьютор **не должен о нём знать вообще**.

2024-11-29 17:14 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +    auto &msg = messages[0];
Ok.

2024-11-29 17:14 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +        for (auto spike : spikes_per_group[i]) result.push_back(spike);
По-идее, ты **не знаешь** тип спайка.

2024-11-29 17:18 UTC, artiomn commented on knp/base-framework/impl/message_handler.cpp
> +    for (auto spike : spikes)
Ты не знаешь тип: сегодня - элементарный, завтра - класс.

2024-12-04 11:04 UTC, artiomn approved these changes

2024-12-04 11:05 UTC, merged